package org.ucombinator.jade.interpreter

package object classfile {
  import TypeCommons.JavaIdentifier
  import scala.language.implicitConversions
  // The grammar includes the terminal symbol `Identifier` to denote the name of
  // a type, field, method, formal parameter, local variable, or type variable,
  // as generated by a Java compiler.
  def isSignatureIdentifierCharacter(char: Char): Boolean = { !".;[/<>:".contains(char) }

  // Helper so we can use a `String` as an `Identifier`
  implicit def stringToIdentifier(string: String): JavaIdentifier = JavaIdentifier(string)

}
